import * as React from "react";
import type { HeadFC, PageProps } from "gatsby";
import {
  Box,
  Center,
  Heading,
  Highlight,
  List,
  ListItem,
  Text,
  useColorMode,
  Code,
  Button,
  calc,
  CodeProps,
  Link as ChakraLink,
  Divider,
  Flex,
  Image,
  BoxProps,
  Stack,
} from "@chakra-ui/react";
import { css, keyframes } from "@emotion/react";
import { Service } from "../Components/Service";
import { FloatingAnimation } from "../utils";
import { title } from "process";
import WithSubnavigation from "../Layout/TopNav";

const $lineHeight = "1rem";

const PurpleCode = (props: CodeProps) => (
  <Code colorScheme="purple" {...props} />
);

const IndexPage: React.FC<PageProps> = () => {
  const { toggleColorMode } = useColorMode();
  return (
    <Box as="main">
      <WithSubnavigation />
      <Center height={"100%"} textAlign="center" mt={"50px"}>
        <Flex gap={$lineHeight} flexDir="column">
          <Heading
            as="h1"
            size="4xl"
            lineHeight={calc($lineHeight).multiply(4).toString()}
            color={"#1A365D"}
          >
            <Highlight
              query="With Speed"
              styles={{ color: "purple.600", _dark: { color: "purple.400" } }}
            >
              Resilience Tech
            </Highlight>
          </Heading>
          <Text fontSize={["2xl", "4xl"]} fontWeight={"bold"} color={"#4A5568"}>
            Mission statement
          </Text>
          <Center>
            <Text fontSize={["1xl", "2xl"]} w={["100%", "100%", "100%", "50%"]}>
              We are dedicated to empowering small and medium-sized businesses
              in the UK to thrive in today’s rapidly evolving technological
              landscape. Through our expertise in data analytics and site
              reliability engineering, we help these businesses build resilient
              IT systems that balance innovation with business continuity. By
              addressing the unique challenges faced by UK SMEs — from the high
              costs of forming skilled teams to the complexities of maintaining
              operational resilience — we enable them to focus on their core
              business, explore new opportunities, and make calculated decisions
              with confidence. Our mission is to reduce their pain points and
              enhance their capacity to sustain growth and success.
            </Text>
          </Center>
        </Flex>
      </Center>
      <Center>
        <Box w={["100%", "100%", "100%", "50%"]}>
          <Stack spacing={6}>
            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Number of SMBs
              </Text>
              <Text>
                As of 2023, there are approximately 5.5 million small and
                medium-sized businesses in the UK, accounting for 99.9% of all
                private sector businesses.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Employment
              </Text>
              <Text>
                SMBs employ around 61% of the private sector workforce, which is
                equivalent to 16.4 million people. Small businesses alone (those
                with 0-49 employees) employ about 48% of the private sector
                workforce.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Contribution to the Economy
              </Text>
              <Text>
                SMBs contribute about 52% of the turnover generated by the
                private sector in the UK, amounting to around £2.3 trillion.
                They are responsible for around 50% of the UK’s GDP, showcasing
                their critical role in the overall economic performance.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Regional Distribution
              </Text>
              <Text>
                London has the highest concentration of SMBs, accounting for
                approximately 19% of all UK businesses. Other regions with a
                significant number of SMBs include the South East and North
                West, representing 15% and 10% of the total, respectively.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Growth and Innovation
              </Text>
              <Text>
                In recent years, SMBs have been at the forefront of innovation,
                with around 50% of UK SMBs investing in new technologies,
                including digital tools and automation, to improve their
                business processes. The growth rate of SMBs in the technology
                sector has been particularly notable, with a yearly increase of
                around 10% in the number of tech-related SMBs.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Impact of COVID-19
              </Text>
              <Text>
                During the COVID-19 pandemic, SMBs were significantly impacted,
                with around 80% reporting a drop in revenue in 2020. However,
                many adapted by increasing their online presence, with about 43%
                of small businesses enhancing their digital capabilities.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Export Contribution
              </Text>
              <Text>
                SMBs contribute approximately 33% of the UK's total export
                value, with a significant portion of these exports going to the
                European Union, followed by the United States and other non-EU
                countries.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Access to Finance
              </Text>
              <Text>
                Around 41% of SMBs in the UK report challenges in accessing
                finance, with traditional bank loans being the primary source of
                funding. However, alternative finance options, such as
                crowdfunding and peer-to-peer lending, are becoming more
                popular.
              </Text>
            </Box>

            <Box p={4}  borderRadius="md" boxShadow="md">
              <Text fontSize="lg" fontWeight="bold">
                Sectoral Distribution
              </Text>
              <Text>
                The largest sectors for SMBs in the UK are professional,
                scientific, and technical services, which make up about 15% of
                all SMBs. Other significant sectors include construction (13%),
                wholesale and retail trade (11%), and administrative and support
                services (8%).
              </Text>
            </Box>
          </Stack>
        </Box>
      </Center>
    </Box>
  );
};

export default IndexPage;

export const Head: HeadFC = () => <title>Resilience Tech</title>;

const blinking = keyframes`
  0% { opacity: 0 }
  100% { opacity: 1} 
`;

export const Foxinfo = (
  props: BoxProps & {
    title: string | React.ReactElement;
    description: string | React.ReactElement;
    order: number;
    image?: React.ReactElement;
    textPosition?: "right" | "left";
  }
) => {
  const [state, setState] = React.useState(false);
  React.useLayoutEffect(() => {
    setTimeout(
      () => {
        setState(true);
      },
      1000 * (props.order - 1) + 1000
    );
  }, [props]);

  if (!state) return;

  return (
    <Box
      w={"450px"}
      h={"100px"}
      position={"absolute"}
      {...props}
      css={css`
        animation: ${blinking};
        animation-duration: 0.1s;
        animation-iteration-count: 5;
        animation-timing-function: ease-in-out;
      `}
    >
      <Flex
        alignItems={"top"}
        gap={["5px"]}
        flexDirection={props.textPosition === "left" ? "row-reverse" : "row"}
        textAlign={props.textPosition === "left" ? "right" : "left"}
      >
        <Box w={"100px"}>{props.image}</Box>
        <Box w={"340px"}>
          <Heading fontSize={"28px"} color={"#E85816"}>
            {props.title}
          </Heading>
          <Text color={"#1A365D"}>{props.description}</Text>
        </Box>
      </Flex>
    </Box>
  );
};
